name: AdvancedBan
author: balugaq
description: This is a Slimefun addon.
main: com.balugaq.advancedban.implementation.AdvancedBan
website: https://github.com/balugaq/AdvancedBan
version: ${project.version}
api-version: 1.17
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
commands:
  advancedban:
    aliases:
      - ab
      - advancedban
    description: /advancedban
    usage: /advancedban <sub>
